### PR TITLE
Fix unexpected ; in RemoveLayoutCommand.php

### PR DESCRIPTION
**Pull request by crouillon**

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
@crouillon afaik it's valid in heredoc syntax: does this semicolon break something?

**Comment by crouillon** [comment]
yes, the command cannot be launch (on windows platform at least, but it seems to be a syntax error)

**Comment by mickaelandrieu** [comment]
Ok :) lucky for us that you still use Windows!

**Comment by crouillon** [comment]
:v:

**Comment by ndufreche** [comment]
:+1:

**Pull request merged**
